name: Python CI  # Name of the workflow

on:
  push:
    branches: [main]  # Runs when code is pushed to the 'main' branch
  pull_request:
    branches: [main]  # Runs when a pull request is created for 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # The virtual machine where the job runs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clones the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run tests
        run: |
          pytest  # Runs tests using pytest (modify if using a different test framework)

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./test-results/  # Adjust if your test results are stored elsewhere
